# PrestaShop
#
# VERSION 0.1
# DOCKER-VERSION 0.2
 
from ubuntu:12.04
# make sure the package repository is up to date
run echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
run apt-get update
 
# Install lamp and unzip
run apt-get install -y apache2 php5 libapache2-mod-php5 unzip php5-gd php5-mysql
# Install mysql-server in non-interactive mode
run bash -c "export DEBIAN_FRONTEND=noninteractive; apt-get -q -y install mysql-server-5.5"
 
# Make mysql listen on the outside
run sed -i 's/127.0.0.1/0.0.0.0/' /etc/mysql/my.cnf
 
# Retrieve PrestaShop's sources, unzip them and set the permissions
copy http://www.prestashop.com/download/old/prestashop_1.5.4.1.zip /var/www/prestashop.zip
run unzip /var/www/prestashop.zip -d /var/www/
run chown -R www-data:www-data /var/www/prestashop
 
# Retrieve the template for the settings
copy https://raw.github.com/jbarbier/PrestaShop/master/.docker/settings.inc.php /var/www/prestashop/config/settings.inc.php.template
